apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-daemon
  namespace: default
spec:
  selector:
    matchLabels:
      name: test-daemon
  template:
    metadata:
      labels:
        name: test-daemon
    spec:
      containers:
        - name: bash
          image: debian:10-slim
          args: ["sleep", "infinity"]
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
      hostNetwork: true
      tolerations:
        # this toleration is to have the daemonset runnable on master nodes
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
