---
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - kms:
          name: sops
          endpoint: unix:///var/lib/etcd/sops.sock
          cachesize: 100
          timeout: 3s
      - identity: {}
